### ISSUE TITLE
rp/repack

### ISSUE THREAD

**Issue by lordimac** [PCJones/radarr-sonarr-german-dual-language#1]
Hello, sometimes my files are ending with -rp or -repack. How to edit the regex so the format also recognizes these titles?

**Comment by PCJones** [comment]
Hi, are you talking about German DL releases? Can you give an example filename and what exactly you want to achieve or what's the problem?

**Comment by lordimac** [comment]
Sorry, was a bad naming from the group. It detected -rp as rls group not as repack.
