### ISSUE TITLE
Grabbing incorrect (english) files instead of existing german ones

### ISSUE THREAD

**Issue by Shyrux** [PCJones/radarr-sonarr-german-dual-language#12]
Hey,
i did the setup for sonarr with pref on only german if both do not exist. Most of the time it works but on some episodes it grabs the wrong language. 

Here as example Foundation S1E6 it grabs this episode:
![grafik](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/114941451/d9807943-5534-440e-943c-55dfe34cbd4a)

But if I do an interactive search I can finde episodes like this:
![grafik](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/114941451/50195889-cd91-4c11-8137-f3b8fc6498d1)

Profile used:
![grafik](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/114941451/a0a21c9a-5996-41f9-8f77-150e6c62692e)

More ot less the same problem here, but atleast it shows some "error" which I do not understand:
![grafik](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/114941451/85a7de6e-902c-4e0d-b741-ee10f27f86ae)

![grafik](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/114941451/f6699631-3f5e-4de1-b158-1ee4b9afef8b)

What is that v2?

**Comment by PCJones** [comment]
1.) Go to Settings->Media Management
2.) Make sure Advanced Settings are enabled at the top
3.) Scroll down to File Management
4.) Set Propers and Repacks to Do not Prefer

that should fix it, forgot to mention it in the guide, sorry!

**Comment by Shyrux** [comment]
That helped wonders, thank you! And no worries your guide is awesome, opend a whole new world for me :)
