### ISSUE TITLE
Selten deutsches Audio

### ISSUE THREAD

**Issue by L4ma** [PCJones/radarr-sonarr-german-dual-language#17]
Hi, 
ich habe zwar alles so eingerichtet, wie bei deiner Anleitung, allerdings habe ich oft das Problem, dass die Filme nur mit englischer Audio heruntergeladen werden. Wie kann ich das anpassen, dass nur Filme in Deutsch heruntergeladen werden? Sobald es keine deutsche Audio gibt, soll nichts heruntergeladen werden. 

<img width="1410" alt="image" src="https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/26965333/c8aca123-8c88-48f2-91d4-34464bef26d1">
<img width="1273" alt="image" src="https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/26965333/fca36b1e-547e-4128-8f8e-86a54d6aa4c4">

Ich spreche übrigens von Radarr.

Danke dir/euch schon mal!

**Comment by PCJones** [comment]
Hast du das Problem damals noch gelöst? Du hast das ja direkt geschlossen, deshalb hab ichs leider übersehen

**Comment by L4ma** [comment]
Ja, das Problem konnte ich lösen. Deshalb auch die schnelle Schließung. :)
