### ISSUE TITLE
"WEBDL-1080p" Source wrong?

### ISSUE THREAD

**Issue by Sim0nW0lf** [PCJones/radarr-sonarr-german-dual-language#2]
When I tried your "WEBDL-XXXXp" profile it didn't rate my WEBDL-XXXXp indexed files properly. I changed the Source in these custom profiles to "Web" and then it was working. What do you think? Am I doing something wrong there?

**Comment by PCJones** [comment]
Thanks for reporting it!
Did you import it into Sonarr or into Radarr?

**Comment by Sim0nW0lf** [comment]
I tried both but had this issue only in Sonarr.
Maybe it's because I am running the development channel and not the :latest docker image?

**Comment by PCJones** [comment]
WEBDL was wrong for Sonarr, WebRip wrong for Radarr. I wrongly assumed that they are using the same internal IDs. I added individual custom formats for Radarr and Sonarr each. Can you confirm if that fixes it?

**Comment by Sim0nW0lf** [comment]
The new imports worked nicely, thank you very much!👍🏻

I was about to think about exactly how I could manage languages when I discovered your project on Reddit. It just worked perfectly immediately, so thank you very much for your work on this 😊👏🏻
