### ISSUE TITLE
Unable to Import Automatically: Not a Custom Format upgrade…

### ISSUE THREAD

**Issue by cospeedster** [PCJones/radarr-sonarr-german-dual-language#22]
Hi, I stumbled oder the following error. What did I missed out in my configuration of sonarr to enable the update?

![IMG_5779](https://github.com/user-attachments/assets/b7c22678-1be3-41e4-8442-e56a26bbb1c8)

![IMG_5780](https://github.com/user-attachments/assets/f156bc07-cce7-42cb-963c-6e6102e02e4d)

![IMG_5781](https://github.com/user-attachments/assets/4bf48df0-7003-4291-8dab-450500540994)

![IMG_5782](https://github.com/user-attachments/assets/3ff85ec7-94db-4b88-9229-46c9275b28d6)

![IMG_5783](https://github.com/user-attachments/assets/cc1cb21f-471f-4efc-b255-9a3827ee6e3f)

I also want to thank you for the sharing of your work here! :)

**Comment by PCJones** [comment]
Anime automation is pure pain. If you open the history for that specific episode (by clicking on the episode name in the show overview), which Custom Formats does the release have when it's being grabbed? (You might need to enable the custom format column in the upper right corner).

Example of what I'm looking for:
![grafik](https://github.com/user-attachments/assets/86aa91e1-7a15-4320-8755-fd7f66e2c038)

**Comment by cospeedster** [comment]
Hey, thanks for your quick reply. It‘s not an anime series.

Although I have misread the error message. The newly downloaded release has a lower score. So it‘s completely okay that it not get imported.

However, it‘s confusing because I don‘t understand why the new release was downloaded. Have you any idea on that?

**Comment by PCJones** [comment]
Yes and to see why I need to see the episode history, that's why I asked for it :P

**Comment by cospeedster** [comment]
Hey, today it happens again:

![image](https://github.com/user-attachments/assets/531a5e5f-ca7f-47d9-aa61-258e491199c7)

![image](https://github.com/user-attachments/assets/ca87e48e-12f1-4fb2-aaf2-48ee7254fa06)

**Comment by cospeedster** [comment]
I ended up setting `Minimum Custom Format Score` to `15000`. I hope this will fix that behavior.

**Comment by PCJones** [comment]
Can you try to set minimum score to 0 again and then:

1.) Go to Settings->Media Management
2.) Make sure Advanced Settings are enabled at the top
3.) Scroll down to File Management
4.) Set Propers and Repacks to Do not Prefer

that should fix it

**Comment by cospeedster** [comment]
Thanks for your advice. I've done that in the meantime in combination with the minimum custom format score and it seems to work for me. :-)
