### ISSUE TITLE
Mehr eine Sonarr-Problematik - Deutsche Serientitel

### ISSUE THREAD

**Issue by ListGrey** [PCJones/radarr-sonarr-german-dual-language#25]
Hallo,

tolle Arbeit, die mir schon sehr geholfen hat. Aber eines bekomme ich nicht hin, und ich suche, aber werde aus den Antworten nicht schlau.

Wenn mein Indexer eine Serie nur unter "Die Arbeiter german 1080p" (erfundenes Beispiel) listet, Sonarr aber die Serie unter "The worker" listet (auch wenn in TVDB "Die Arbeiter" als alternativer Titel steht), dann findet Sonarr diese Serie nie, ganz unabhängig von den hier veröffentlichten Costum Profiles?

Vielen Dank im Voraus.

**Comment by PCJones** [comment]
Hi,

hast du zufällig discord? Wir haben da eine sehr nette hilfsbereite Community zum Thema Usenet, Torrent, Radarr/Sonarr, Jelllyfin/Plex & co. Da können wir dir bestimmt helfen :)

https://discord.gg/pZrrMcJMQM


Zu deinem eigentlichen Problem:
Das ist tatsächlich sehr doof und die Entwickler von Sonarr zeigen da auch keine Einsicht. Glücklicherweise habe ich aber genau aus dem Grund ein eigenes Tool geschrieben, dass die deutschen sowie die alternativen Titel von TVDB korrekt erkennt und in die englischen Titel umbenannt, so dass Sonarr diese problemlos downloadet und importiert: https://github.com/PCJones/UmlautAdaptarr

Falls du kein docker nutzt meld dich gerne, es geht zur Not auch ohne
