### ISSUE TITLE
Custom Format scheint bei Single Language nicht zu greifen

### ISSUE THREAD

**Issue by Durone01** [PCJones/radarr-sonarr-german-dual-language#26]
Ist mir erst heute aufgefallen, aber wenn es nur eine deutsche Tonspur gibt, dann scheint das Custom Format nicht zu greifen. Es rechnet dann nicht die 25000 Punkte für German Language drauf sondern nur die (bei mir eingestellten 3000 Punkte) für das Bluray 720p release.
![grafik](https://github.com/user-attachments/assets/fc35ea98-8473-4241-b0cd-bc5b148db18b)

Ich vermute es liegt am German DL 2 Format. Weil wenn ich da das Englisch rausnehme, dann rechnet er wieder richtig die 25k Punkte drauf. 
![grafik](https://github.com/user-attachments/assets/296a2a24-adf1-41ef-a94f-058829c9ac4c)

Ich vermute also dass es eine AND Verknüpfung ist und sowohl DE als auch EN da sein muss, um den Trigger für German DL 2 zu kriegen. 
![grafik](https://github.com/user-attachments/assets/93b02a8e-cb49-473a-b8ff-0be4c711e963)

**Comment by Durone01** [comment]
Ok, da hat jemand den Guide nicht richtig gelesen... Es ist ja explizit ein Dual Language guide. :) dann macht es natürlich Sinn das Single Language aussortiert wird.

**Comment by PCJones** [comment]
Wenn du den Guide ganz durcharbeitest hast du auch ein "German only" custom format :)
https://github.com/PCJones/radarr-sonarr-german-dual-language?tab=readme-ov-file#8-prefer-language
