### ISSUE TITLE
Not upgrading

### ISSUE THREAD

**Issue by Sim0nW0lf** [PCJones/radarr-sonarr-german-dual-language#3]
Hey, do you maybe have an idea why it doesn't upgrade? Or do you have similar issues? To me it looks like a Radarr problem but I thought maybe you know something 😅

![Screenshot_20230827_051911_com chrome dev_edit_20956345706177](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/31454341/4cf4c287-7d1d-4bd0-9242-79e58f718fb9)
![Screenshot_20230827_051329](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/31454341/d2d93061-3ac9-4e8f-9b97-64c7aa77c02e)
![Screenshot_20230827_051410](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/31454341/3a616a93-32d0-41c1-b388-fce1c24b1245)

**Comment by Sim0nW0lf** [comment]
Another example:

It would download this: Iron.Man.2.2010.REAL.PROPER.1080p.BluRay.x264-TONYSTARK
but not this: Iron.Man.2.2010.German.DTS.DL.1080p.BluRay.x264-VIAHD

even tho the score is much higher and the other one is English not German...

**Comment by PCJones** [comment]
Does this fix it?

1.) Go to Settings->Media Management
2.) Make Advanced Settings are enabled at the top
3.) Scroll down to File Management
4.) Set Propers and Repacks to Not Prefer

**Comment by Sim0nW0lf** [comment]
OMG thank you so much! I would have never found that 😮

Worked immediately and the correct releases are being grabbed 👍🏻🎉

**Comment by PCJones** [comment]
Yeah I should've added it to the guide, I didn't because I forgot about the settings myself

**Comment by AdamVB** [comment]
@PCJones thanks for the solution, stumbled upon the same issue! Would've never found out otherwise!
