### ISSUE TITLE
Multilanguage not recognized 

### ISSUE THREAD

**Issue by Sim0nW0lf** [PCJones/radarr-sonarr-german-dual-language#4]
For some reason very often my multilanguage files are not being recognized correctly. Do you know why that could be?

![Screenshot_20230828_213906](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/31454341/3e20dabe-6e7f-4353-89e9-4f8c15dd19e0)

**Comment by PCJones** [comment]
Probably because the (original) filename doesn't contain German DL. I'll let you know when I updated the guide to handle this

**Comment by Sim0nW0lf** [comment]
Thanks! :)

Also odd to me is that Sonarr often doesn't recognize language correctly even tho it shows in the file overview:
![image](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/31454341/ef28c6dd-d2f1-4205-9d23-a400691a494c)
But here it should see that its actually multilanguage and also german:
![image](https://github.com/PCJones/radarr-sonarr-german-dual-language/assets/31454341/df27bb3e-918a-48ce-a424-27d983eff0df)

**Comment by Sim0nW0lf** [comment]
Managed to make it work by just filtering for languages in a custom format and giving it the same score as the text based search score. Including {MediaInfo Simple} in the filename helps to manage format and audio.

**Comment by PCJones** [comment]
This should be fixed now with a second custom format:

https://github.com/PCJones/radarr-sonarr-german-dual-language/blob/main/README.md#1-import-the-german-dl-custom-formats

If your solution is better please share your custom format(s) :)

**Comment by Sim0nW0lf** [comment]
Yes that's how I did it too 👍🏻
