### ISSUE TITLE
Payed support?

### ISSUE THREAD

**Issue by CurlyFlow** [PCJones/radarr-sonarr-german-dual-language#7]
Hi, do you wanna set it up for me? Sonarr und Radarr is working fine and i have some sort of "prefer german" inplace, which mostly work, but i would really like to have a more robust setup because some releases dont get picked up.

Do you offer some setup service? maybe 50€?

**Comment by PCJones** [comment]
Please add me on discord or Telegram.

https://github.com/PCJones/radarr-sonarr-german-dual-language#contact--support
